language: python
sudo: false

addons:
  apt:
    packages:
    - xmlsec1

matrix:
  include:
    - python: 3.4
      env: TOXENV=py34
    - python: 3.5 # not yet pre-installed in Travis base image
      env: TOXENV=py35


install:
  - pip install -U tox

script:
  - tox